name: Lint

on:
  workflow_dispatch:
  push:
    branches: [ci-lint]
  pull_request:
    branches: [ci-lint]

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.0

      - name: Install dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
