name: Go CI

on:
  workflow_dispatch:
  push:
    branches: [ci-build, ci-test]
  pull_request:
    branches: [ci-build, ci-test]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.0

      - name: Check Go version
        run: go version

      - name: Install dependencies
        run: GOPROXY=direct go mod tidy

      - name: Build
        run: go build -v ./cmd/server

      - name: Test
        run: go test -v ./...
